-- Demo / fixture data for local development.
--
-- Reference Quran data (surahs and ayahs) is loaded from db/seed_quran.sql,
-- which is applied first by `make db-seed`. This file is reserved for demo
-- fixtures (mock users, sample attempts, etc.) that should NOT be derived
-- from the upstream Quran dataset.
--
-- Add new fixtures below as needed.
